// packages/cli/src/adapters/frontend/angular.adapter.ts
/**
 * Angular frontend adapter.
 *
 * @module adapters/frontend/angular
 */

import { writeFileTree } from "../../utils/utils.fileSystem.js";
import { normalizeName } from "../../utils/utils.name.js";
import { scaffoldWithFallback } from "../../scaffolders/scaffolder.helper.js";
import type {
  FrontendAdapter,
  FrontendGenerationContext,
  DependencyRequirement,
  ValidationResult,
} from "./frontendAdapter.type.js";

/**
 * Angular adapter with standalone support.
 */
export class AngularAdapter implements FrontendAdapter {
  readonly name = "angular";
  readonly framework = "angular";

  async isAvailable(): Promise<boolean> {
    return true;
  }

  async getLatestVersion(): Promise<string> {
    return "19.0.0";
  }

  async scaffold(context: FrontendGenerationContext): Promise<void> {
    const files = this.getBaseFiles(context);
    // Angular CLI requires a valid project name; "." is not one. Pass the
    // real name and scaffold into the current directory via --directory.
    const projectName = normalizeName(context.project.name) || "zudojs-app";
    await scaffoldWithFallback({
      command: "npx",
      args: [
        "@angular/cli@latest",
        "new",
        projectName,
        "--directory",
        ".",
        "--skip-git",
        "--skip-install",
        "--routing",
        "--style",
        "css",
        "--standalone",
      ],
      targetPath: context.projectPath,
      fallbackFiles: files,
    });
  }

  getDependencies(
    context: FrontendGenerationContext,
  ): readonly DependencyRequirement[] {
    const deps: DependencyRequirement[] = [];

    if (context.features.stateManagement === "ngrx") {
      deps.push({ name: "@ngrx/store", type: "dependency" });
    }

    if (context.features.testing) {
      deps.push(
        { name: "@angular/core", type: "dependency" },
        { name: "@angular/common", type: "dependency" },
        { name: "jest", type: "devDependency" },
        { name: "@angular-builders/jest", type: "devDependency" },
      );
    }

    return deps;
  }

  async applyZudojsStructure(
    context: FrontendGenerationContext,
  ): Promise<void> {
    const structure = this.getStructure(context);
    await writeFileTree(context.projectPath, structure);
  }

  async generateIntegration(context: FrontendGenerationContext): Promise<void> {
    const integrationFiles = this.getIntegrationFiles(context);
    await writeFileTree(context.projectPath, integrationFiles);
  }

  async validate(
    context: FrontendGenerationContext,
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    const warnings: string[] = [];

    if (!context.project) {
      errors.push("Project configuration is required");
    }

    return { valid: errors.length === 0, errors, warnings };
  }

  private getBaseFiles(
    context: FrontendGenerationContext,
  ): Record<string, string> {
    return {
      "package.json": JSON.stringify(
        {
          name: context.project.name,
          version: "0.0.0",
          private: true,
          scripts: {
            start: "ng serve",
            build: "ng build",
            test: "ng test",
          },
          dependencies: {
            "@angular/animations": "^19.0.0",
            "@angular/common": "^19.0.0",
            "@angular/compiler": "^19.0.0",
            "@angular/core": "^19.0.0",
            "@angular/forms": "^19.0.0",
            "@angular/platform-browser": "^19.0.0",
            "@angular/platform-browser-dynamic": "^19.0.0",
            "@angular/router": "^19.0.0",
            rxjs: "~7.8.0",
            tslib: "^2.3.0",
            "zone.js": "~0.15.0",
          },
          devDependencies: {
            "@angular-devkit/build-angular": "^19.0.0",
            "@angular/cli": "^19.0.0",
            "@angular/compiler-cli": "^19.0.0",
            "@types/jasmine": "~5.1.0",
            "jasmine-core": "~5.1.0",
            karma: "~6.4.0",
            typescript: "~5.6.0",
          },
        },
        null,
        2,
      ),
      "tsconfig.json": JSON.stringify(
        {
          compileOnSave: false,
          compilerOptions: {
            outDir: "./dist/out-tsc",
            strict: true,
            noImplicitOverride: true,
            noPropertyAccessFromIndexSignature: true,
            noImplicitReturns: true,
            noFallthroughCasesInSwitch: true,
            esModuleInterop: true,
            sourceMap: true,
            declaration: false,
            downlevelIteration: true,
            experimentalDecorators: true,
            moduleResolution: "bundler",
            importHelpers: true,
            target: "ES2022",
            module: "ES2022",
            lib: ["ES2022", "dom"],
            useDefineForClassFields: true,
          },
          angularCompilerOptions: {
            enableI18nLegacyMessageIdFormat: false,
            strictInjectionParameters: true,
            strictInputAccessModifiers: true,
            strictTemplates: true,
          },
        },
        null,
        2,
      ),
      "src/main.ts": `import { bootstrapApplication } from "@angular/platform-browser";
import { AppComponent } from "./app/app.component";

bootstrapApplication(AppComponent);
`,
      "src/index.html": `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>${context.project.name}</title>
    <base href="/" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  </head>
  <body>
    <app-root></app-root>
  </body>
</html>
`,
      "src/app/app.component.ts": `import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  standalone: true,
  template: "<h1>Hello from Zudojs</h1>",
})
export class AppComponent {}
`,
    };
  }

  private getStructure(
    context: FrontendGenerationContext,
  ): Record<string, string> {
    return {
      "src/app/components/.gitkeep": "",
      "src/app/pages/.gitkeep": "",
      "src/app/services/.gitkeep": "",
      "src/app/utils/.gitkeep": "",
      "src/app/types/index.ts": "// Types\nexport {};\n",
      "src/assets/.gitkeep": "",
      "src/environments/.gitkeep": "",
    };
  }

  private getIntegrationFiles(
    context: FrontendGenerationContext,
  ): Record<string, string> {
    const files: Record<string, string> = {};

    if (context.project.type === "fullstack") {
      files[".env.example"] = `API_URL=http://localhost:3000\n`;

      files["src/app/services/api-client.ts"] = `/**
 * API Client for backend communication.
 */

const API_URL = "http://localhost:3000";

export interface ApiResponse<T> {
  readonly data: T;
  readonly status: number;
}

export async function apiGet<T>(path: string): Promise<ApiResponse<T>> {
  const response = await fetch(\`\${API_URL}\${path}\`);
  const data = await response.json() as T;
  return { data, status: response.status };
}

export async function apiPost<T>(path: string, body: unknown): Promise<ApiResponse<T>> {
  const response = await fetch(\`\${API_URL}\${path}\`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const data = await response.json() as T;
  return { data, status: response.status };
}
`;
    }

    return files;
  }
}

// packages/cli/src/adapters/frontend/react.adapter.ts
/**
 * React frontend adapter using Vite.
 *
 * @module adapters/frontend/react
 */

import { execCommand } from "../../utils/utils.exec.js";
import { writeFileTree } from "../../utils/utils.fileSystem.js";
import { scaffoldWithFallback } from "../../scaffolders/scaffolder.helper.js";
import type {
  FrontendAdapter,
  FrontendGenerationContext,
  DependencyRequirement,
  ValidationResult,
} from "./frontendAdapter.type.js";

/**
 * React adapter using Vite as the build tool.
 */
export class ReactAdapter implements FrontendAdapter {
  readonly name = "react";
  readonly framework = "react";

  async isAvailable(): Promise<boolean> {
    try {
      await execCommand("node", ["--version"], ".");
      return true;
    } catch {
      return false;
    }
  }

  async getLatestVersion(): Promise<string> {
    return "19.0.0";
  }

  async scaffold(context: FrontendGenerationContext): Promise<void> {
    const files = this.getBaseFiles(context);
    await scaffoldWithFallback({
      command: "npm",
      args: [
        "create",
        "vite@latest",
        ".",
        "--",
        "--template",
        context.language === "javascript" ? "react" : "react-ts",
      ],
      targetPath: context.projectPath,
      fallbackFiles: files,
    });
  }

  getDependencies(
    context: FrontendGenerationContext,
  ): readonly DependencyRequirement[] {
    const deps: DependencyRequirement[] = [
      { name: "react", type: "dependency" },
      { name: "react-dom", type: "dependency" },
    ];

    if (context.features.stateManagement === "zustand") {
      deps.push({ name: "zustand", type: "dependency" });
    }

    if (context.features.testing) {
      deps.push(
        { name: "vitest", type: "devDependency" },
        { name: "@testing-library/react", type: "devDependency" },
        { name: "@testing-library/jest-dom", type: "devDependency" },
        { name: "@testing-library/user-event", type: "devDependency" },
        { name: "jsdom", type: "devDependency" },
      );
    }

    if (context.features.linting) {
      deps.push(
        { name: "eslint", type: "devDependency" },
        { name: "typescript-eslint", type: "devDependency" },
        { name: "eslint-plugin-react-hooks", type: "devDependency" },
        { name: "eslint-plugin-react-refresh", type: "devDependency" },
      );
    }

    if (context.features.formatting) {
      deps.push({ name: "prettier", type: "devDependency" });
    }

    return deps;
  }

  async applyZudojsStructure(
    context: FrontendGenerationContext,
  ): Promise<void> {
    const structure = this.getStructure(context);
    await writeFileTree(context.projectPath, structure);
  }

  async generateIntegration(context: FrontendGenerationContext): Promise<void> {
    const integrationFiles = this.getIntegrationFiles(context);
    await writeFileTree(context.projectPath, integrationFiles);
  }

  async validate(
    context: FrontendGenerationContext,
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    const warnings: string[] = [];

    if (!context.project) {
      errors.push("Project configuration is required");
    }

    return { valid: errors.length === 0, errors, warnings };
  }

  private getBaseFiles(
    context: FrontendGenerationContext,
  ): Record<string, string> {
    const useTypeScript = context.language === "typescript";
    const ext = useTypeScript ? "tsx" : "jsx";

    return {
      "package.json": JSON.stringify(
        {
          name: context.project.name,
          version: "0.1.0",
          private: true,
          type: "module",
          scripts: {
            dev: "vite",
            // Vite performs the build; tsc only typechecks (noEmit).
            build: useTypeScript ? "tsc --noEmit && vite build" : "vite build",
            preview: "vite preview",
          },
          dependencies: {
            react: "^19.0.0",
            "react-dom": "^19.0.0",
          },
          devDependencies: {
            vite: "^6.0.0",
            "@vitejs/plugin-react": "^4.3.0",
            ...(useTypeScript ? { typescript: "^5.0.0" } : {}),
          },
        },
        null,
        2,
      ),
      "vite.config.ts": `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
`,
      ...(useTypeScript
        ? {
            "tsconfig.json": JSON.stringify(
              {
                compilerOptions: {
                  target: "ES2020",
                  useDefineForClassFields: true,
                  lib: ["ES2020", "DOM", "DOM.Iterable"],
                  module: "ESNext",
                  skipLibCheck: true,
                  moduleResolution: "bundler",
                  allowImportingTsExtensions: true,
                  resolveJsonModule: true,
                  jsx: "react-jsx",
                  noEmit: true,
                },
              },
              null,
              2,
            ),
          }
        : {}),
      "index.html": `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${context.project.name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.${ext}"></script>
  </body>
</html>
`,
      [`src/main.${ext}`]: `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";

createRoot(document.getElementById("root")${useTypeScript ? "!" : ""}).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
`,
      [`src/App.${ext}`]: `export default function App() {
  return (
    <div>
      <h1>Hello from Zudojs</h1>
    </div>
  );
}
`,
      ...(useTypeScript
        ? { "src/vite-env.d.ts": `/// <reference types="vite/client" />\n` }
        : {}),
    };
  }

  private getStructure(
    context: FrontendGenerationContext,
  ): Record<string, string> {
    const srcDir = "src";

    if (context.architecture === "feature-based") {
      return this.getFeatureBasedStructure(srcDir);
    }

    if (context.architecture === "minimal") {
      return this.getMinimalStructure(srcDir);
    }

    return this.getZudojsStandardStructure(srcDir);
  }

  private getZudojsStandardStructure(srcDir: string): Record<string, string> {
    return {
      [`${srcDir}/components/.gitkeep`]: "",
      [`${srcDir}/configs/index.ts`]: "// Configuration\nexport {};\n",
      [`${srcDir}/constants/index.ts`]: "// Constants\nexport {};\n",
      [`${srcDir}/contexts/.gitkeep`]: "",
      [`${srcDir}/hooks/.gitkeep`]: "",
      [`${srcDir}/layouts/.gitkeep`]: "",
      [`${srcDir}/pages/.gitkeep`]: "",
      [`${srcDir}/routes/index.tsx`]: "// Routes\nexport {};\n",
      [`${srcDir}/services/.gitkeep`]: "",
      [`${srcDir}/stores/.gitkeep`]: "",
      [`${srcDir}/types/index.ts`]: "// Types\nexport {};\n",
      [`${srcDir}/utils/.gitkeep`]: "",
    };
  }

  private getFeatureBasedStructure(srcDir: string): Record<string, string> {
    return {
      [`${srcDir}/features/.gitkeep`]: "",
      [`${srcDir}/components/.gitkeep`]: "",
      [`${srcDir}/hooks/.gitkeep`]: "",
      [`${srcDir}/services/.gitkeep`]: "",
      [`${srcDir}/types/index.ts`]: "// Types\nexport {};\n",
      [`${srcDir}/utils/.gitkeep`]: "",
    };
  }

  private getMinimalStructure(srcDir: string): Record<string, string> {
    return {
      [`${srcDir}/components/.gitkeep`]: "",
      [`${srcDir}/utils/.gitkeep`]: "",
    };
  }

  private getIntegrationFiles(
    context: FrontendGenerationContext,
  ): Record<string, string> {
    const files: Record<string, string> = {};

    if (context.project.type === "fullstack") {
      files[".env.example"] = `VITE_API_URL=http://localhost:3000\n`;

      files["src/services/api-client.ts"] = `/**
 * API Client for backend communication.
 */

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:3000";

export interface ApiResponse<T> {
  readonly data: T;
  readonly status: number;
}

export async function apiGet<T>(path: string): Promise<ApiResponse<T>> {
  const response = await fetch(\`\${API_URL}\${path}\`);
  const data = await response.json() as T;
  return { data, status: response.status };
}

export async function apiPost<T>(path: string, body: unknown): Promise<ApiResponse<T>> {
  const response = await fetch(\`\${API_URL}\${path}\`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const data = await response.json() as T;
  return { data, status: response.status };
}

export async function apiPut<T>(path: string, body: unknown): Promise<ApiResponse<T>> {
  const response = await fetch(\`\${API_URL}\${path}\`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const data = await response.json() as T;
  return { data, status: response.status };
}

export async function apiDelete<T>(path: string): Promise<ApiResponse<T>> {
  const response = await fetch(\`\${API_URL}\${path}\`, {
    method: "DELETE",
  });
  const data = await response.json() as T;
  return { data, status: response.status };
}
`;
    }

    return files;
  }
}
